### PR TITLE
update to 1.20.1

### PR DESCRIPTION
**Pull request by JacktheDevel0per**
You can remove any comments with -Jack at the end, they are just there to show places that could be simplified.
(If you want I can just remove them)

Tell me if anything is not how you would like it. Hope this is not a really bad PR.

### CODE REVIEW

**Comment by JacktheDevel0per** [comment]
I have tested ever game version for launch and the careful drop rule; 1.19.4 and 1.20.1 for the casting changes so far.

**Comment by senseiwells** [comment]
Haha, I was just starting this tonight, but I guess you saved me some time, thanks.

I will probably review this tomorrow evening and will probably make some minor adjustments.

**Comment by JacktheDevel0per** [comment]
the build failed because it ran out of memory xD

**Comment by sternschnaube** [comment]
Thank you @JacktheDevel0per 😊
I had problems to build it either.

Hope it gets released the next days.

**Review by senseiwells — APPROVED** [review]
Looks good

**Pull request merged**
